### PR TITLE
[GHA] Fixing Production build action branch commit

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
Fix the error in github action:

```bash
fatal: invalid refspec 'HEAD:'
```

**Comment by samsonasik** [comment]
@TomasVotruba let's try this, I think it is ready.

**Comment by TomasVotruba** [comment]
Let's try it :)

**Comment by samsonasik** [comment]
@TomasVotruba it seems got error: 

```bash
remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: error: 8 of 8 required status checks are expected.        
To https://github.com/rectorphp/getrector.org
 ! [remote rejected] HEAD -> main (protected branch hook declined)
error: failed to push some refs to 'https://github.com/rectorphp/getrector.org'
```

**Comment by TomasVotruba** [comment]
Good job Github :) Commiting to `main` branch is not a good idea.
Coud you find a way to update `composer.lock` without pushing - only for the build?

**Comment by TomasVotruba** [comment]
Please revert this ASAP, so we have passing build. 

Make sure new work is done in standalone workflow that won't block the build. Thanks

**Comment by samsonasik** [comment]
Yes, probably need "automatic pull request" workflow for it.

**Pull request merged**
