### PR TITLE
[GHA] Fix action/checkout github token

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba the current daily pull request automatic update got error:

```bash
Run actions/checkout@v2

Error: Input required and not supplied: token
```

ref https://github.com/rectorphp/getrector.org/runs/2505391808?check_suite_focus=true#step:2:1

It may be because `${{ secrets.ACCESS_TOKEN }}` not exists, could you verify if it is should be `${{ secrets.ACCESS_TOKEN }}` or `{{ $secrets.GITHUB_TOKEN }}` in this repo?

**Comment by TomasVotruba** [comment]
Hi, I've checked it now and added `ACCESS_TOKEN`

**Comment by TomasVotruba** [comment]
I've just retriggered the workflow

**Comment by samsonasik** [comment]
@TomasVotruba thank you, it seems working now https://github.com/rectorphp/getrector.org/pull/317 , I am closing it.

**Pull request closed without merging**
