### PR TITLE
Automated framework migration 1

### PR DESCRIPTION
**Pull request by rajyan**

### CODE REVIEW

**Comment by rajyan** [comment]
@TomasVotruba 

This post is ready!

**Comment by TomasVotruba** [comment]
That's awesome, thank you :+1: 

I'll review and publish in a bit :)

**Comment by TomasVotruba** [comment]
I've reviewed few grammar details and added few spaces.
See PR https://github.com/rectorphp/getrector.org/pull/492

**Comment by rajyan** [comment]
Thanks, closing this one

**Pull request closed without merging**
