### PR TITLE
Brand new Design

### PR DESCRIPTION
**Pull request by TomasVotruba**
# Blog Before

image

-----

# Blog After

image

### CODE REVIEW

**Comment by TomasVotruba** [comment]
# Demo Before

image


-----

# Demo After

image

**Comment by TomasVotruba** [comment]
# Footer Before

image


---


# Footer Now

image

**Comment by TomasVotruba** [comment]
# Homapage Before

rector_old

<br>
<br>
<br>
<br>
<br>

# Homepage Now

rector_now

**Comment by TomasVotruba** [comment]
# Homepage Now

rector_now

**Comment by TomasVotruba** [comment]
Let's shipt it :)

**Comment by Kerrialn** [comment]
@TomasVotruba need to fix text size on small devices. 

IMG_5468F0086EB9-1

**Comment by TomasVotruba** [comment]
Indeed, I'll look on it, thanks

**Pull request merged**
