### PR TITLE
Display Rector version at demo page

### PR DESCRIPTION
**Pull request by samsonasik**
@TomasVotruba this is display Rector vesion at demo page:

Screen Shot 2022-08-20 at 17 10 58

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
rebased.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Comment by TomasVotruba** [comment]
Btw, could you make the text grey, so it does not take that much attention?

The day of version release could be also important, to determine how old the deployed version is. Could you add it?

**Comment by samsonasik** [comment]
I will try, the PackageVersion doesn't show the date, so it probably need to directly read from composer.lock

https://github.com/rectorphp/getrector.org/blob/872a6ae0fd1a99c41fd2dea288a8f0860c57ba7d/composer.lock#L667

**Comment by TomasVotruba** [comment]
The date time is stored in this constant:
https://github.com/rectorphp/rector/blob/0be9fe255157e4140c86c4dbbfa9a347f3ae6997/src/Application/VersionResolver.php#L25

**Comment by samsonasik** [comment]
https://github.com/rectorphp/getrector.org/pull/721

**Pull request merged**
