### PR TITLE
[Rector Config] Add Option::PHPSTAN_FOR_RECTOR_PATH to rector config

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
What is the motivation for this?

**Comment by samsonasik** [comment]
I checked the patch of https://github.com/rectorphp/rector/pull/5781 seems not applied in getrector.org/demo , is it maybe probably by this or because of pending update in the getrector.org site ?

**Comment by TomasVotruba** [comment]
Website demo is not deployed as result of merge here.

Last was 3 days ago: https://github.com/rectorphp/getrector.org

**Comment by samsonasik** [comment]
Ok :+1:

**Pull request closed without merging**
