### PR TITLE
Fix daily PR: use symplify/amnesia:10.2.7

### PR DESCRIPTION
**Pull request by samsonasik**
@TomasVotruba the current daily PR got error:

```bash
Run composer update rector/rector phpstan/phpdoc-parser --with-all-dependencies
Loading composer repositories with package information
Info from [https://repo.packagist.org:](https://repo.packagist.org/) #StandWithUkraine
Updating dependencies
Your requirements could not be resolved to an installable set of packages.
Error: Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Root composer.json requires symplify/amnesia ^11.0, found symplify/amnesia[dev-main, 9.0.39, ..., 9.4.70, 10.0.0-beta1, ..., 10.3.x-dev (alias of dev-main)] but it does not match the constraint.
```

because symplify/amnesia:^11.0 is not exists. I updated to "10.2.7 as 11.0" for latest release for it.

Fixes https://github.com/rectorphp/getrector.org/issues/628

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
I try to fix it here https://github.com/rectorphp/getrector.org/commit/18a14154ab21e632021f7123a3601319d7f2c2f8

**Comment by samsonasik** [comment]
The code is using symplify/amnesia classe, so that Will error

**Comment by samsonasik** [comment]
@TomasVotruba thank you for the fix 👍

**Pull request closed without merging**
