### PR TITLE
Display grey rector release time

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba it show the grey text and release date time: 

Screen Shot 2022-08-20 at 20 27 56

**Comment by TomasVotruba** [comment]
Thank you :+1: 

Just first 6 chars of the commits hash is enough. It would also more readable information

**Comment by samsonasik** [comment]
Updated to only show 6 chars hash commit

Screen Shot 2022-08-20 at 20 42 38

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
This is amazing, thank you :+1:

**Pull request merged**
