### PR TITLE
Add logo variant featuring both text and the house

### PR DESCRIPTION
**Pull request by honzajavorek**
I downloaded the Montserrat font and tried to reproduce the logo as it is on the website, but in Inkscape so it can be featured as a standalone SVG logo.

### CODE REVIEW

**Comment by honzajavorek** [comment]
Hmm, in the preview here I noticed the SVG isn't cropped for some reason. I'll try to fix that.

**Comment by TomasVotruba** [comment]
Wohoo, thank you for this work!

Not sure if I'm seeing it right. Maybe I miss some local fonts...

Here:

image


On website:

image

**Comment by honzajavorek** [comment]
Huh, I see it right, probably because I have the font installed now :) I’ll
see if I can force Inkscape to include the letters as curves instead, so
it's independent on system fonts.

**Comment by TomasVotruba** [comment]
If it's a problem to include the font and it helps you solve the missing logo, I can merge it.

**Comment by honzajavorek** [comment]
Dont merge yet, I’ll update the PR with the letters as curves. It must have
solution, its a common practice. I just thought Inkscape did it
automatically as I couldn’t notice it did not :))

**Comment by TomasVotruba** [comment]
All right, just ping me when it's ready :)

**Comment by honzajavorek** [comment]
Does it display better now?

**Comment by TomasVotruba** [comment]
Better :+1: 

https://github.com/rectorphp/getrector.org/pull/173/files?short_path=8b10bce#diff-8b10bcefa798e66cf68ef789312f007a

image


:clap: 

How difficult is to make also white variant? So we can use it instead of current text-picture mixed logo in the future

**Comment by honzajavorek** [comment]
I think it should be easy-ish, another 15mins of work at maximum.

**Comment by honzajavorek** [comment]
Could you verify if works correctly? (As you don't have Montserrat font installed, I'd have to uninstall it first to verify.)

**Comment by TomasVotruba** [comment]
Pufrect! Now we're a serious company :), thanks :+1: 

image

**Comment by honzajavorek** [comment]
🚀

**Pull request merged**
