### PR TITLE
Update back rector to use dev-main

### PR DESCRIPTION
**Pull request by samsonasik**
@TomasVotruba your commit https://github.com/rectorphp/getrector.org/commit/58f6f0e60df141909df605b0702fbf1c7cd4f4ab was update to use rector ^0.14, that will make per-6 hours update not applied as will wait for next release.

This PR update back to use dev-main to get faster feedback after fix applied to dev-main.

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
I see. My goal was to trigger update to the latest release.
I wonder we could show the current commit + tag version on Rector demo page. It would make reports clear to specific version.

**Comment by samsonasik** [comment]
Maybe we can use https://packagist.org/packages/ocramius/package-versions

**Comment by samsonasik** [comment]
https://github.com/rectorphp/getrector.org/pull/719

**Pull request merged**
