### PR TITLE
Revert "Update docker setup (#251)"

### PR DESCRIPTION
**Pull request by TomasVotruba**
This reverts commit 4a03bd7a249eae6b79b7a4f3716cb97f4fabac2e.

Hotfix for 2 Docker bugs on Linux:

- https://github.com/rectorphp/getrector.org/pull/251#issuecomment-777072338
- https://github.com/rectorphp/getrector.org/pull/254#issuecomment-777079386

Feel free to revert when a propper fix is ready. I need to make some fixes on demo form now, so I need working Docker form

### CODE REVIEW

**Comment by JanMikes** [comment]
Pls no panic revert, im here to help you (can you give it few mins?). As it works on production and tested on 2 different OS (macos, ubuntu) i suspect there is something with your machine.

Please: rm -rf repository, git clone and `docker-compose up` -> do fresh startup, tested 5 times now on ubuntu.

**Comment by JanMikes** [comment]
FIrst guess, think it could be cased by `.env.local` existing in your repository, check if it exists and if yes, delete it as well in case you dont want to do fresh startup.

**Comment by TomasVotruba** [comment]
I'll give it try after the fix

**Comment by TomasVotruba** [comment]
I'll give it try after the fix

**Comment by TomasVotruba** [comment]
I'll give it try after the fix

**Comment by JanMikes** [comment]
Nice! 👌 im here to help you in realtime, on any channel, whatsapp, telegram, messenger, sms, choose your favorite 😸

**Comment by ruudk** [comment]
@TomasVotruba Are you running Docker (compose) with sudo by any chance? 

See https://stackoverflow.com/a/61905266
https://docs.docker.com/engine/install/linux-postinstall/

That could explain why `$PWD` is empty. 

I think we should try to fix it like it was, because then it would just work by default, without having to specify any paths.

**Comment by TomasVotruba** [comment]
@ruudk Yes, always. Otherwise I get these errors:

https://github.com/symplify/symplify/blob/1353bd6ae212d520f7b7a43902e83edae8c91bcb/tests/bootstrap.php#L21

**Comment by ruudk** [comment]
@TomasVotruba wrong link? It doesn't show the errors

**Comment by TomasVotruba** [comment]
@ruudk I'm sorry, I got confused with another issue. I've updated the image

**Comment by ruudk** [comment]
https://stackoverflow.com/a/52798075  Seems like your `/var/run/docker.sock` needs a chown.

**Comment by ruudk** [comment]
Or follow these steps, https://docs.docker.com/engine/install/linux-postinstall/ 

You should not have to run it with sudo.

**Comment by TomasVotruba** [comment]
I would need exact steps, as I don't have the skill to work with bash and user access rights.

**Pull request merged**
