### PR TITLE
[Test] Add Acceptance test to avoid unknown error 500

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/getrector.org/issues/700

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
Tested ok 👍 

Screen Shot 2022-08-21 at 19 23 49

**Comment by TomasVotruba** [comment]
Thank you

**Pull request merged**
