### PR TITLE
May 2019 update

### LINKED ISSUE #13: Add private projects that used Rector
- Entrydo
- Elasticr

### LINKED ISSUE #23: Add table with project show case and numbers
E.g. entryfo, 50 k lines, 80 hours, 2 people in one work week, migration of nette framework go Symfony

### LINKED ISSUE #24: Ultimate goal
Q: "So what is your ultimate goal with Rector? What do you want to do?" 

<em>Martin Victor Newham</em>

↓

A: "Help every code in the planet change their code on daily basis."

### LINKED ISSUE #25: Add tailor-made elevator pitches
Inspired by Symfony page: https://symfony.com/what-is-symfony

image

### LINKED ISSUE #29: Add joindin feedback on web
https://joind.in/event/php-russia-2019/how-to-make-legacy-refactoring-fun-again---from-months-to-days

### LINKED ISSUE #31: [feedback] use direct tweets instead copy-paste
Inspired by https://slides.com/about?root=true

image

### LINKED ISSUE #32: Add patreon support

### PR DESCRIPTION
**Pull request by TomasVotruba**
- closes #25 
- closes #29 
- closes #24 
- closes #13 
- closes #31
- closes #23
- closes #32

### CODE REVIEW

**Comment by TomasVotruba** [comment]
## Before

before


## After

after


@JanMikes Cca 70 % done. Could you give me 3 worst points feedback now? :)

**Comment by JanMikes** [comment]
1) Header is just awful, we have to hire a design guy (not bad for a start though) 😄 
2) Gif with demo is too awkard (it would look awesome in some kind of screen or terminal window example on black background) - [inspiration](https://www.google.com/imgres?imgurl=https%3A%2F%2Fimages-wixmp-ed30a86b8c4ca887773594c2.wixmp.com%2Ff%2F16ede2e6-0102-4cc4-a83b-83836bb6cc88%2Fd9mkpmj-ca0deb5a-f443-4e97-9d09-8c47530f2563.png%3Ftoken%3DeyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzE2ZWRlMmU2LTAxMDItNGNjNC1hODNiLTgzODM2YmI2Y2M4OFwvZDlta3Btai1jYTBkZWI1YS1mNDQzLTRlOTctOWQwOS04YzQ3NTMwZjI1NjMucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.UfW4CUO8qYEDnLzBwypgs2xu8FlbZCDa3-Nx7xJ4r8M&imgrefurl=https%3A%2F%2Fwww.deviantart.com%2Fpowerup1163%2Fart%2FTerminal-app-mockup-582113467&docid=tdVsTz5l85MVbM&tbnid=L-X2O0hDzmde-M%3A&vet=10ahUKEwjEpfSgrbziAhVBJ1AKHdclBS4QMwhLKAwwDA..i&w=958&h=704&client=safari&bih=907&biw=1680&q=terminal%20mockup&ved=0ahUKEwjEpfSgrbziAhVBJ1AKHdclBS4QMwhLKAwwDA&iact=mrc&uact=8#h=704&imgdii=yQqFtGki7DLIrM:&vet=10ahUKEwjEpfSgrbziAhVBJ1AKHdclBS4QMwhLKAwwDA..i&w=958)
3) The "what people say" is awesome, i love that!

**Comment by TomasVotruba** [comment]
1. nothing I can do here, PNG format is well accepted :)

2. oh, so colors only? I'll probably use asciinema: https://asciinema.org/a/225151, I think about good example - small but effective, any ideas?

3.

**Comment by JanMikes** [comment]
1. I know, as i said, we will hire graphics guy 😄 
2. 1000 times better! Im not sure if the `git diff` step is necesarry, othervise very nice demo, use this one, it is swaggy! :octocat:

**Pull request merged**
