### PR TITLE
Automated framework migration 2

### PR DESCRIPTION
**Pull request by rajyan**

### CODE REVIEW

**Comment by rajyan** [comment]
@TomasVotruba 

This one is ready too!

**Comment by TomasVotruba** [comment]
Thank you, I'm on the review :+1:

**Comment by TomasVotruba** [comment]
I'll merge this PR and send another with fixups. The deployment is now stopped

**Comment by TomasVotruba** [comment]
Thank you for your work and time you've put into this :+1: 

We'll publish and share it probably some time next week.

**Comment by rajyan** [comment]
@TomasVotruba 
Your welcome!
I hope this can help the PHP community. 

Thank you very much too for the great open source works! They saved plenty of our time.

**Comment by TomasVotruba** [comment]
Glad I could help :bow:

**Pull request merged**
